title: "Marlon Calispa"
description: "Soil Science | GIS | Remote Sensing"
author: "Marlon Calispa"

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
