title: "Marlon Calispa"
name: "Marlon Calispa"
description: "Soil Science | GIS | Remote Sensing"
url: "https://marloncalispa.github.io"
baseurl: ""  # keep empty for user.github.io repos

# Theme
remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache   # ✅ fixed

# Site settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Author info 
author:
  name   : "Marlon Calispa"
  avatar : "/images/FAceFront.jpg"
  bio    : "Researcher in soil sciences, GIS, and remote sensing."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:marlon@example.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/marloncalispa"

# Navigation (from _data/navigation.yml)
