title: "Marlon Calispa"
name: "Marlon Calispa"
description: "Soil Science | GIS | Remote Sensing"
url: "https://marloncalispa.github.io"
baseurl: ""  # keep empty for user.github.io repos

# Theme
#Innocent test
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Site settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Collections (build underscored folders) 
collections:
  pages:
    output: true
    permalink: /:path/
  publications:
    output: true
    permalink: /:collection/:name/

# Author info
author:
  name: "Marlon Calispa"
  avatar: "/images/FAceFront.jpg"   # <-- change to your actual filename
  bio: "Researcher in soil sciences, GIS, and remote sensing."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "marloncalispa@gmail.com"
    - label: "Research Gate"
      icon: "fab fa-researchgate"
      url: "https://www.researchgate.net/profile/Marlon-Calispa"
