title: "Marlon Calispa"
description: "Soil Science | GIS | Remote Sensing"
author: "Marlon Calispa"
theme: minima   # start simple; later you can switch to Minimal Mistakes or AcademicPages
baseurl: ""     # leave empty for user.github.io
url: "https://marloncalispa.github.io"

# Navigation (will pull from _data/navigation.yml if using a custom theme)
collections:
  publications:
    output: true
    permalink: /publications/:path/

markdown: kramdown
